# Site settings
title: Ryley Higa
email: ryley.higa2@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a machine learning engineer for Sumo Logic interested in AI safety and transparency.
slogan: >
  Machine learning engineer for Sumo Logic
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
linkedin_username: ryleyhiga
github_username:  rhiga2

# Build settings
markdown: kramdown

paginate: 4

author: Ryley Higa

gems: [jekyll-paginate]
