# Site settings
title: Ryley Higa
email: ryley.higa2@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a machine learning engineer for Sumo Logic that creates human-in-the-loop AI tools for prductivity, 
  troubleshooting, and safety.
slogan: >
  Senior Machine learning Engineer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rhiga2.github.io/" # the base hostname & protocol for your site
linkedin_username: ryleyhiga
github_username:  rhiga2

# Build settings
markdown: kramdown

paginate: 4

author: Ryley Higa

gems: [jekyll-paginate]
